### ISSUE TITLE
Cannot find module webpack-merge

### ISSUE THREAD

**Issue by stanleyck** [besLisbeth/arcgis-offline-tiles#1]
Hi, 

Just discovered this repo and it looks really promising. However, the demo application seems to be down, and when downloading the demo repo myself and running npm start (after install) I get an error cannot find module 'webpack-merge'. 

Any idea how I can fix this?

**Comment by stanleyck** [comment]
Nevermind. The issue was wrong configuration on my side.

**Comment by besLisbeth** [comment]
Hi @stanleyck. Thank you for the nice response.
Did you find out why the demo didn't work for you? Because I just checked that everything works as it should.
