### ISSUE TITLE
NPM fails to get src folder

### ISSUE THREAD

**Issue by nxbaggio** [besLisbeth/arcgis-offline-tiles#13]
When I attempt use "npm install arcgis-offline_tiles" I do end up getting the packages, but it fails to pull in the folder "src".

**Comment by besLisbeth** [comment]
Hi @nxbaggio, what version of `webpack` do you use? I created the demo in the branch `demo-sources` where I installed the package via `webpack 4.44`. Unfortunately, I currently have no time to update the dependencies here
